use master
go

DROP database IF EXISTS dbMarket;

CREATE DATABASE dbMarket;
GO

USE dbMarket;
GO

set language spanish;
GO


DROP TABLE IF EXISTS PERSONA ;
CREATE TABLE PERSONA  (
    IDPER		int NOT NULL IDENTITY (200,1),
	DNIPER		varchar(40)  NOT NULL,
	NOMPER		varchar(40)  NOT NULL,
	APEPER		varchar(40)  NOT NULL,
	AMAPER		varchar(80)  NOT NULL,
	CELPER		char(9)  NOT NULL,
	TIPPER		char(1)  NOT NULL,
	ESTPER		char(1) DEFAULT 'A',
	FECNACPER	datetime DEFAULT GETDATE()  NOT NULL,
    CONSTRAINT PERSONA_pk PRIMARY KEY(IDPER)
);
GO

INSERT INTO PERSONA (DNIPER,NOMPER,APEPER,AMAPER,CELPER,TIPPER,FECNACPER)
VALUES  ('77889955','Alberto','Solano Pariona','alberto.pariona@empresa.com','998456321','V','10/2/1970'),
		('45781233','Alicia','García Campos','alicia.garcia@gmail.com','929185236','C','20/3/1980'),
		('15487922','Juana','Ávila Chumpitaz','juana.avila@gmail.com','923568741','C','6/6/1986'),
		('22116633','Ana','Enriquez Flores','ana.enriquez@empresa.com','978848551','V','10/2/1970'),
		('88741589','Claudia','Perales Ortíz','claudia.perales@yahoo.com','997845263','C','25/7/1981'),
		('45122587','Mario','Barrios Martínez','mario.barrios@outlook.com','986525874','C','10/10/1987'),
		('15258564','Brunela','Tarazona Guerra','brunela.tarazona@gmail.com','986525877','C','6/6/1990');

DROP TABLE IF EXISTS CATEGORIA  ;
CREATE TABLE CATEGORIA   (
    IDCAT int NOT NULL IDENTITY (10,10),
	NOMCAT varchar(40)  NOT NULL,
    CONSTRAINT CATEGORIA_pk PRIMARY KEY  (IDCAT)
);
GO

INSERT INTO CATEGORIA (NOMCAT)
VALUES  ('Abarrotes'),
		('Carnes y Pollo'),
		('Higiene y Limpieza');

DROP TABLE IF EXISTS PRODUCTO   ;
CREATE TABLE PRODUCTO    (
    CODPROD varchar(3)  NOT NULL,
	NOMPRO varchar(40)  NOT NULL,
	PREPRO decimal(10,2)  NOT NULL,
	STOCKPRO int  NOT NULL,
	IDCAT int  NOT NULL ,
	ESTPRO char(1) DEFAULT 'A',
    CONSTRAINT CODPROD_pk PRIMARY KEY  (CODPROD)
);
GO

INSERT INTO PRODUCTO (CODPROD,NOMPRO,PREPRO,STOCKPRO,IDCAT)
VALUES  ('PO1','Arroz','4.65','50','10'),
		('PO2','Azúcar','3.45','60','10'),
		('PO3','Pollo fresco','8.70','20','20'),
		('PO4','Lomo fino','18.50','40','20'),
		('PO5','Detergente Opal','8.75','60','30'),
		('PO6','Suavizante Ariel','7.85','30','30');

DROP TABLE IF EXISTS VENTA;
CREATE TABLE VENTA(
    IDVEN		int NOT NULL IDENTITY (1,1),
	FECVEN		datetime DEFAULT GETDATE()  NOT NULL,
	IDVEND		int  NOT NULL , 
	IDCLI		int  NOT NULL ,
	TIPPAGVEN	char(1)  NOT NULL,
	IDPER		int NOT NULL,
	ESTVEN		char(1) DEFAULT 'A',
    CONSTRAINT VENTA_pk PRIMARY KEY  (IDVEN)
);
GO

INSERT INTO VENTA (IDVEND,IDCLI,TIPPAGVEN,IDPER)
VALUES  ('200','202','E','202'),
		('200','204','T','204'),
		('203','205','T','205'),
		('203','206','E','206');

DROP TABLE IF EXISTS VENTA_DETALLE ;
CREATE TABLE VENTA_DETALLE(
    IDVENDET int NOT NULL IDENTITY (300,1),
	IDVEN int NOT NULL, 
	CODPROD varchar(3)  NOT NULL,
	CANVENDET int  NOT NULL ,
    CONSTRAINT IDVENDET_pk PRIMARY KEY (IDVENDET)
);
GO

INSERT INTO VENTA_DETALLE (IDVEN,CODPROD,CANVENDET)
VALUES  ('1','PO1','2'),
		('1','PO4','4');

---la relación de las tablas PRODUCTO y CATEGORIA.
ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_CATEGORIA
    FOREIGN KEY (IDCAT)
    REFERENCES CATEGORIA (IDCAT);

---relación de VENTA_DETALLE con VENTA y PRODUCTO.
ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_VENTA
    FOREIGN KEY (IDVEN)
    REFERENCES VENTA (IDVEN);

---relación de VENTA_DETALLE con VENTA y PRODUCTO.
ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_PRODUCTO
    FOREIGN KEY (CODPROD)
    REFERENCES PRODUCTO (CODPROD);

---relaciones de la tabla VENTA con la tabla PERSONA
ALTER TABLE VENTA ADD CONSTRAINT VENTA_PERSONA
    FOREIGN KEY (IDPER)
    REFERENCES PERSONA (IDPER);


SELECT * FROM  VENTA
SELECT * FROM  PERSONA
SELECT * FROM  CATEGORIA
SELECT * FROM  PRODUCTO
SELECT * FROM  VENTA_DETALLE
