use master
go

DROP database IF EXISTS dbMarket;

CREATE DATABASE dbMarket;
GO

USE dbMarket;
GO

set language spanish;
GO


DROP TABLE IF EXISTS PERSONA ;
CREATE TABLE PERSONA  (
    IDPER int NOT NULL ,
	DNIPER varchar(40)  NOT NULL,
	NOMPER varchar(40)  NOT NULL,
	APEPER varchar(40)  NOT NULL,
	AMAPER varchar(80)  NOT NULL,
	CELPER char(9)  NOT NULL,
	TIPPER char(1)  NOT NULL,
	ESTPER char(1) DEFAULT 'A',
	FECNACPER date  NOT NULL,
    CONSTRAINT PERSONA_pk PRIMARY KEY  (IDPER)
);
GO

INSERT INTO PERSONA (IDPER,DNIPER,NOMPER,APEPER,AMAPER,CELPER,TIPPER,FECNACPER)
VALUES  ('200','77889955','Alberto','Solano Pariona','alberto.pariona@empresa.com','998456321','V','10/2/1970'),
		('201','45781233','Alicia','García Campos','alicia.garcia@gmail.com','929185236','C','20/3/1980'),
		('202','15487922','Juana','Ávila Chumpitaz','juana.avila@gmail.com','923568741','C','6/6/1986'),
		('203','22116633','Ana','Enriquez Flores','ana.enriquez@empresa.com','978848551','V','10/2/1970'),
		('204','88741589','Claudia','Perales Ortíz','claudia.perales@yahoo.com','997845263','C','25/7/1981'),
		('205','45122587','Mario','Barrios Martínez','mario.barrios@outlook.com','986525874','C','10/10/1987'),
		('206','15258564','Brunela','Tarazona Guerra','brunela.tarazona@gmail.com','986525877','C','6/6/1990');

DROP TABLE IF EXISTS CATEGORIA  ;
CREATE TABLE CATEGORIA   (
    IDCAT int  NOT NULL,
	NOMCAT varchar(40)  NOT NULL,
    CONSTRAINT CATEGORIA_pk PRIMARY KEY  (IDCAT)
);
GO

INSERT INTO CATEGORIA (IDCAT,NOMCAT)
VALUES  (10,'Abarrotes'),
		(20,'Carnes y Pollo'),
		(30,'Higiene y Limpieza');

DROP TABLE IF EXISTS PRODUCTO   ;
CREATE TABLE PRODUCTO    (
    CODPROD varchar(5)  NOT NULL,
	NOMPRO varchar(40)  NOT NULL,
	PREPRO decimal(10,2)  NOT NULL,
	STOCKPRO int  NOT NULL,
	IDCAT int  NOT NULL ,
	ESTPRO char(1) DEFAULT 'A',
    CONSTRAINT CODPROD_pk PRIMARY KEY  (CODPROD)
);
GO

INSERT INTO PRODUCTO (CODPROD,NOMPRO,PREPRO,STOCKPRO,IDCAT)
VALUES  ('PO1','Arroz','4.65','50','10'),
		('PO2','Azúcar','3.45','60','10'),
		('PO3','Pollo fresco','8.70','20','20'),
		('PO4','Lomo fino','18.50','40','20'),
		('PO5','Detergente Opal','8.75','60','30'),
		('PO6','Suavizante Ariel','7.85','30','30');

DROP TABLE IF EXISTS VENTA;
CREATE TABLE VENTA     (
    IDVEN int  IDENTITY (1,1)NOT NULL,
	FECVEN date  NOT NULL,
	IDVENDL int  NOT NULL , 
	IDCLI int  NOT NULL ,
	TIPPAGVEN char(1)  NOT NULL,
	ESTVEN char(1) DEFAULT 'A',
    CONSTRAINT VENTA_pk PRIMARY KEY  (IDVEN)
);
GO

INSERT INTO VENTA (FECVEN,IDVENDL,IDCLI,TIPPAGVEN)
VALUES  ('25/10/2022','200','202','E'),
		('25/10/2022','200','204','T'),
		('25/10/2022','203','205','T'),
		('25/10/2022','203','206','E');

DROP TABLE IF EXISTS VENTA_DETALLE ;
CREATE TABLE VENTA_DETALLE(
    IDVENDET int  NOT NULL,
	IDVEN int  NOT NULL , 
	CODPROD varchar(5)  NOT NULL,
	CANVENDET int  NOT NULL ,
    CONSTRAINT IDVENDET_pk PRIMARY KEY (IDVENDET)
);
GO

INSERT INTO VENTA_DETALLE (IDVENDET,IDVEN,CODPROD,CANVENDET)
VALUES  ('300','1','PO1','2'),
		('301','1','PO4','4');

SELECT * FROM PRODUCTO
SELECT * FROM CATEGORIA


---la relación de las tablas PRODUCTO y CATEGORIA.
ALTER TABLE CATEGORIA ADD CONSTRAINT CATEGORIA_CATEGORIA
    FOREIGN KEY (IDCAT)
    REFERENCES CATEGORIA (IDCAT);


SELECT * FROM VENTA_DETALLE
SELECT * FROM VENTA
---relación de VENTA_DETALLE con VENTA y PRODUCTO.
ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_VENTA
    FOREIGN KEY (IDVEN)
    REFERENCES VENTA (IDVEN);

SELECT * FROM VENTA_DETALLE
SELECT * FROM PRODUCTO
---relación de VENTA_DETALLE con VENTA y PRODUCTO.
ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_PRODUCTO
    FOREIGN KEY (CODPROD)
    REFERENCES PRODUCTO (CODPROD);